# Generated by Django 6.0.6 on 2026-06-16 18:31
from django.db import migrations


def copy_teacher_to_teachers(apps, schema_editor):
    Student = apps.get_model('school', 'Student')
    db_alias = schema_editor.connection.alias

    students = Student.objects.using(db_alias).exclude(teacher_id__isnull=True)

    for student in students.iterator():
        student.teachers.add(student.teacher_id)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teachers_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_teacher_to_teachers, migrations.RunPython.noop),
    ]
