# Generated by Django 6.0.6 on 2026-06-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_copy_teacher_to_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
